name: 'Continuous Integration'

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install linter
        run: pip install ruff

      - name: Run linter
        run: ruff check challenge/ tests/

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Verify code structure
        run: |
          python -c "from challenge.api import app; print('API module OK')"
          python -c "import challenge; print('Package OK')"

      - name: Test API health endpoint
        run: |
          uvicorn challenge.api:app --host 0.0.0.0 --port 8000 &
          sleep 10
          curl -f http://localhost:8000/health

